// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pixeqpezgahkpjiisjih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpeGVxcGV6Z2Foa3BqaWlzamloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyNzc5NjUsImV4cCI6MjA5NDg1Mzk2NX0.e0u76-07Yh0UjTE5ZzZ18yPjdy6Wgtn4IjItykBOaeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});